# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Security Client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CryptoSwift', '~> 1.4.1'

end
